// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snwifavoupwrbfjnlgmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNud2lmYXZvdXB3cmJmam5sZ21xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MDM2NDksImV4cCI6MjA3MjI3OTY0OX0._WoLNK9FR7IO8P172n05XrsgztMmJYIQp0rRw2fH0LE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});